project:
  type: website
  output-dir: docs

website:
  favicon: "images/logo.png"
  page-footer: 
    left: |
      Feito com [Quarto](https://quarto.org/)
    right: |
      [Código no Github](https://github.com/ermesonf)
    background: "#181818"
  navbar:
    title: "Ermeson."
    logo: "images/logo.svg"
    right:
      - href: index.qmd
        text: Sobre
      - href: projects.qmd
        text: Portfolio
      - href: resume.qmd
        text: Resumo
      - icon: linkedin
        href: https://linkedin.com/in/ermesonfreitas
      - icon: github
        href: https://github.com/ermesonf/
      - icon: envelope
        href: mailto:ermeson.freitas@hotmail.com
format:
  html:
    theme:
      - cosmos
      - styles.scss
    lang: pt-br
    code-link: true
    code-tools: false
    code-block-bg: "white"
    code-block-border-left: "lightgreen"
    highlight-style: github

editor: visual

